name: Code to-do GitHub Issues backup
description: Scans code base for to-do comments and syncs them to GitHub Issues
runs:
  using: composite
  steps:
  - name: Print the directory before the checkout
    shell: bash
    run: tree
  - name: Check out the workflow ref (detached HEAD)
    uses: actions/checkout@main
  - name: Print the directory after the checkout
    shell: bash
    run: tree
  - name: Print the directory of ${{github.action_path}} before submodule
    shell: bash
    run: |
      cd ${{github.action_path}}
      tree
  - name: Run the action script
    shell: bash
    run: |
      cd ${{github.action_path}}
      git submodule add https://github.com/tomashubelbauer/todo
      node . ${{github.workspace}}
  - name: Print the directory of ${{github.action_path}} after submodule
    shell: bash
    run: |
      cd ${{github.action_path}}
      tree
