name: Code to-do GitHub Issues backup
description: Scans code base for to-do comments and syncs them to GitHub Issues
runs:
  using: composite
  steps:
  - name: Print the directory before the checkout
    shell: bash
    run: |
      echo "Before checkout"
      pwd
      tree -a
  - name: Check out the workflow ref (detached HEAD)
    uses: actions/checkout@main
  - name: Print the directory after the checkout
    shell: bash
    run: |
      echo "After checkout"
      pwd
      tree -a
  - name: Run the action script
    shell: bash
    run: |
      cd ${{github.action_path}}
      git clone https://github.com/tomashubelbauer/todo
      node . ${{github.workspace}} ${{github.token}} ${{github.repository}}
