name: Code to-do GitHub Issues backup
description: Scans code base for to-do comments and syncs them to GitHub Issues
runs:
  using: composite
  steps:
  - name: Check out the workflow ref (detached HEAD)
    uses: actions/checkout@main
  - name: Run the action script
    shell: bash
    run: |
      cd ${{github.action_path}}
      git clone https://github.com/tomashubelbauer/todo
      node . ${{github.workspace}} ${{github.token}} ${{github.repository}} ${{github.server_url}} ${{github.ref_name}}
