name: TODO Comments GitHub Issues
description: Scans code base for TODO comments and syncs them to GitHub Issues.
runs:
  using: composite
  steps:
  - name: Check out the workflow ref (detached HEAD)
    uses: actions/checkout@main
  - name: Run the action script
    shell: bash
    run: |
      cd ${{github.action_path}}
      git clone https://github.com/tomashubelbauer/todo
      node . ${{github.token}}
